# Generated by Django 4.2.6 on 2023-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poliza', models.IntegerField(blank=True, null=True)),
                ('endoso', models.CharField(blank=True, max_length=100, null=True)),
                ('cuota', models.IntegerField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('moneda', models.CharField(max_length=100)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('factura', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cobranzas',
                'ordering': ('poliza',),
            },
        ),
    ]
