# Generated by Django 4.2.6 on 2023-10-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cobranza_aseguradora_cobranza_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranza',
            name='moneda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
