# Generated by Django 4.2.6 on 2024-07-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coberturanominada_linea_de_negocios'),
    ]

    operations = [
        migrations.CreateModel(
            name='AseguradoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asegurado', models.CharField(max_length=40)),
                ('cuit', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=40)),
                ('numero_poliza', models.IntegerField()),
                ('producto', models.CharField(max_length=10)),
                ('fecha_vigencia_desde', models.DateTimeField(blank=True, null=True)),
                ('fecha_vigencia_hasta', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='coberturainnominada',
            name='estadoActual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coberturainnominada',
            name='asegurado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aseguradocredito'),
        ),
        migrations.AddField(
            model_name='coberturanominada',
            name='asegurado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.aseguradocredito'),
        ),
    ]
