# Generated by Django 4.2.6 on 2024-05-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movimiento_premio_con_iva_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='porcentaje_diferencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
