# Generated by Django 4.2.6 on 2024-07-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aseguradocredito_coberturainnominada_estadoactual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aseguradocredito',
            name='fecha_vigencia_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aseguradocredito',
            name='fecha_vigencia_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coberturainnominada',
            name='fecha_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coberturainnominada',
            name='fecha_primer_consulta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coberturainnominada',
            name='fecha_ultima_consulta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coberturanominada',
            name='vigencia_desde',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coberturanominada',
            name='vigencia_hasta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
