# Generated by Django 4.2.6 on 2024-12-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_coberturanominada_vigencia_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coberturanominada',
            name='cobertura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coberturanominada',
            name='monto_temporal',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
