# Generated by Django 4.2.6 on 2023-10-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cobranza_poliza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranza',
            name='cuota',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
