# Generated by Django 4.2.6 on 2023-10-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cobranza_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranza',
            name='cuota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cobranza',
            name='poliza',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
