# Generated by Django 4.2.6 on 2024-12-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coberturanominada_cobertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coberturanominada',
            name='monto_temporal',
            field=models.BigIntegerField(default=0),
        ),
    ]
