# Generated by Django 4.2.6 on 2023-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cobranza_cuota_alter_cobranza_poliza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranza',
            name='poliza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
