# Generated by Django 4.2.6 on 2024-07-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_movimiento_flota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculoflota',
            name='flota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='core.flota'),
        ),
    ]
