# Generated by Django 4.2.6 on 2024-06-10 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente_iibb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='impuestos',
            new_name='imp_y_sellados',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sellados',
        ),
    ]
