# Generated by Django 4.2.6 on 2024-08-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_vehiculoflota_flota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coberturanominada',
            name='monto_aprobado',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='coberturanominada',
            name='monto_solicitado',
            field=models.BigIntegerField(),
        ),
    ]
