# Generated by Django 4.2.6 on 2023-10-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_aseguradora_cobranza_asegurador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranza',
            name='poliza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
