# Generated by Django 4.2.6 on 2023-11-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cobranza_poliza'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cobranza',
            new_name='Vencimiento',
        ),
    ]
