# Generated by Django 4.2.6 on 2023-11-06 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_flota_created_vehiculo_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flota',
            name='created',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='created',
        ),
    ]
