# Generated by Django 4.2.6 on 2023-11-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_flota_created_remove_vehiculo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='flota',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
