# Generated by Django 4.2.6 on 2023-11-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_flota_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaFlota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('zona', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('antiguedad', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_cobertura', models.CharField(blank=True, max_length=100, null=True)),
                ('tasa', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('prima_rc_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='valor',
            new_name='suma_asegurada',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_operacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_vigencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='operacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_cobertura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='zona',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
