# Generated by Django 4.2.6 on 2023-11-17 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flota',
            name='cuit',
        ),
        migrations.RemoveField(
            model_name='flota',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='flota',
            name='email',
        ),
        migrations.RemoveField(
            model_name='flota',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='flota',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='flota',
            name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='flota',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='flota',
            name='telefono',
        ),
        migrations.AddField(
            model_name='flota',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AddField(
            model_name='flota',
            name='numero_flota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flota',
            name='poliza',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
