# Generated by Django 4.2.6 on 2023-11-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_flota_cuit_remove_flota_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='flota',
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('flota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flota')),
            ],
        ),
    ]
