# Generated by Django 4.2.6 on 2023-11-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_movimiento_nombre_movimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vencimiento',
            old_name='asegurador',
            new_name='asegurado',
        ),
    ]
