# Generated by Django 4.2.6 on 2023-11-20 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_asegurador_vencimiento_asegurado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='cod_infoauto',
        ),
    ]
