# Generated by Django 4.2.6 on 2023-11-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_vehiculo_cod_infoauto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='importado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
