# Generated by Django 4.2.6 on 2023-11-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_vehiculo_importado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='prima',
            new_name='premio_anual',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='premio_vigente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='prima_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='prima_vigente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
