# Generated by Django 4.2.6 on 2023-11-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_prima_vehiculo_premio_anual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_operacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
