# Generated by Django 4.2.6 on 2023-11-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_vehiculo_fecha_operacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='cod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
