# Generated by Django 4.2.6 on 2023-12-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_vehiculo_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifaflota',
            name='tasa',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True),
        ),
    ]
