# Generated by Django 4.2.6 on 2023-12-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_premio_anual_vehiculo_premio_con_iva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_access_token', models.CharField(max_length=500)),
                ('encrypted_refresh_token', models.CharField(max_length=500)),
            ],
        ),
    ]
