# Generated by Django 4.2.6 on 2023-12-28 22:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tokenstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('expiracion', models.DateTimeField(default=core.models.access_expiration)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('expiracion', models.DateTimeField(default=core.models.refresh_expiration)),
            ],
        ),
        migrations.DeleteModel(
            name='TokenStorage',
        ),
    ]
