# Generated by Django 4.2.6 on 2023-12-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_accesstoken_refreshtoken_delete_tokenstorage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstoken',
            options={'get_latest_by': 'expiracion'},
        ),
        migrations.AlterModelOptions(
            name='refreshtoken',
            options={'get_latest_by': 'expiracion'},
        ),
    ]
