# Generated by Django 4.2.6 on 2024-01-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_accesstoken_options_alter_refreshtoken_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_provincia', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
