# Generated by Django 4.2.6 on 2024-01-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='zona',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
