# Generated by Django 4.2.6 on 2024-01-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_localidad_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='importado',
        ),
    ]
