# Generated by Django 4.2.6 on 2024-01-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_vehiculo_importado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehiculo',
            new_name='VehiculoFlota',
        ),
    ]
