# Generated by Django 4.2.6 on 2024-01-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_marcainfoauto_vehiculoinfoauto_precioanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculoinfoauto',
            name='precio_okm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
