# Generated by Django 4.2.6 on 2024-01-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_vehiculoinfoauto_precio_okm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioanual',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
