# Generated by Django 4.2.6 on 2024-01-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_precioanual_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculoinfoauto',
            name='precio_okm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
