# Generated by Django 4.2.6 on 2024-01-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_vehiculoinfoauto_precio_okm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculoflota',
            old_name='fecha_operacion',
            new_name='vigencia_desde',
        ),
        migrations.RenameField(
            model_name='vehiculoflota',
            old_name='fecha_vigencia',
            new_name='vigencia_hasta',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='nombre_movimiento',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='tipo_movimiento',
        ),
        migrations.RemoveField(
            model_name='vehiculoflota',
            name='operacion',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_alta_op',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='motivo_endoso',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='numero_endoso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='numero_orden',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='vigencia_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='vigencia_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoflota',
            name='chasis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoflota',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoflota',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoflota',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoflota',
            name='motor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoflota',
            name='observacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoflota',
            name='prima_rc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoflota',
            name='tasa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoflota',
            name='uso_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoflota',
            name='usuario_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoflota',
            name='valor_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
