# Generated by Django 4.2.6 on 2024-01-24 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0040_rename_fecha_operacion_vehiculoflota_vigencia_desde_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVehiculoFlota',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cod', models.IntegerField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_item', models.CharField(blank=True, max_length=255, null=True)),
                ('patente', models.CharField(blank=True, max_length=100, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('okm', models.CharField(blank=True, max_length=100, null=True)),
                ('motor', models.CharField(blank=True, max_length=100, null=True)),
                ('chasis', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('zona', models.CharField(blank=True, max_length=100, null=True)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('uso_vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('suma_asegurada', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('valor_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('tipo_cobertura', models.CharField(blank=True, max_length=100, null=True)),
                ('tasa', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('prima_rc', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('prima_tecnica', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('prima_pza', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('premio_sin_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('premio_con_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.movimiento')),
            ],
            options={
                'verbose_name': 'historical vehiculo flota',
                'verbose_name_plural': 'historical vehiculo flotas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
