# Generated by Django 4.2.6 on 2024-01-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_historicalvehiculoflota'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehiculoflota',
            name='suma_asegurada_accesorios',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehiculoflota',
            name='tiene_accesorios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoflota',
            name='suma_asegurada_accesorios',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculoflota',
            name='tiene_accesorios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
