# Generated by Django 4.2.6 on 2024-01-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_historicalvehiculoflota_suma_asegurada_accesorios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='recargo_financiero',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sellado_impuestos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
