# Generated by Django 4.2.6 on 2024-01-25 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_cliente_iva_cliente_recargo_financiero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculoflota',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movimiento'),
        ),
    ]
